User -> nginx: HTTP
nginx -> Tomcat: HTTP
nginx: {
  Shuffle Sharding
}
Tomcat: {
  style.multiple: true
}
User: {
  shape: person
}
Consumer -> Provider: RPC
Provider: {
  style.multiple: true
}
Consumer: {
  Shuffle Sharding
}
ThreadPool: {
  shape: queue
  Overload Control: {
    shape: text
  }
}
Tomcat -> ThreadPool
Provider -> ThreadPool
ThreadPool -> AppService: inner-process
AppService -> Downstream: RPC
AppService -> DB
AppService -> MQ: produce
AppService -> TransactioanlAsyncTask
TransactioanlAsyncTask -> AsyncTaskThreadPool
AsyncTaskThreadPool: {
  shape: queue
}

MQ -> Instant Queue: re-preduce
Instant Queue: {
  shape: queue
  style.multiple: true
}
Instant Queue -> Listener
